---

CUL:
  symlinks:
    433: CUL433
    868: CUL868


FHEM:
  firware_flash_support: No
  security:
    telnet:
      password: "{{ S_FHEM.security.telnet.password }}"
    web:
      user: fhem
      password: "{{ S_FHEM.security.web.password }}"
  io:
    devices:
      cul:
        433:
          device_path: "/dev/{{ CUL.symlinks.433 }}"
        868:
          device_path: "/dev/{{ CUL.symlinks.868 }}"
  intertechno:
    devices:
      - name: schalter_1A
        code: 000000000F
        alias: Weihnachtsbaum
        group: Licht
        fm_type: offbutton,onbutton,lamp,light
        rooms:
          - Wohnzimmer
          - Homekit
      - name: schalter_1B
        code: 0000F0000F
        alias: "Papierleuchte am Esstisch"
        group: Licht
        fm_type: offbutton,onbutton,lamp
        rooms:
          - Wohnzimmer
          - Homekit
      - name: schalter_1C
        code: 00000F000F
        alias: "Papierleuchte am Fernseher"
        fm_type: offbutton,onbutton,lamp
        group: Licht
        rooms:
          - Wohnzimmer
          - Homekit
  homematic:
    hmId: Lukas


HOMEBRIDGE:
  security:
    username: "{{ S_HOMEBRIDGE.security.username }}"
    pin: "{{ S_HOMEBRIDGE.security.pin }}"
  modules:
    - homebridge
    - homebridge-fhem
    - homebridge-sonos
  accessories:
    - accessory: "Sonos"
      name: "Wohnzimmer Boxen"
      room: "Wohnzimmer"
    - accessory: "Sonos"
      name: "Arbeitszimmer Boxen"
      room: "Arbeitszimmer"
  platforms:
    fhem:
      security:
        user: "{{ FHEM.security.web.user }}"
        password: "{{ FHEM.security.web.password }}"
  nodejs:
    version: node-v4.2.3-linux-armv7l
    download_url: https://nodejs.org/dist/v4.2.3/node-v4.2.3-linux-armv7l.tar.gz


NETWORKING:
  use_wifi: Yes
  interfaces:
    - name: eth0
      config: |+
        auto eth0
        iface eth0 inet dhcp
    - name: wlan0
      config: |+
        allow-hotplug wlan0
        iface wlan0 inet manual
        wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
        iface default inet dhcp
      wifi:
        ssid: PDT-02
        password: "{{ S_NETWORKING.wifi.pdt_02.password }}"
      firmware:
        package: firmware-ralink


UDEV:
  rule_files:
    - name: 99-busware.rules
      rules:
        - 'SUBSYSTEM=="tty", ATTRS{idProduct}=="204b", ATTRS{idVendor}=="03eb", ATTRS{product}=="CUL433", SYMLINK+="{{ CUL.symlinks.433 }}"'
        - 'SUBSYSTEM=="tty", ATTRS{idProduct}=="204b", ATTRS{idVendor}=="03eb", ATTRS{product}=="CUL868", SYMLINK+="{{ CUL.symlinks.868 }}"'
  vendors:
    - 03eb

