---

CUL:
  symlinks:
    433: CUL433
    868: CUL868


FHEM:
  firware_flash_support: Yes

NETWORKING:
  use_wifi: Yes
  interfaces:
    - name: eth0
      config: |+
        auto eth0
        iface eth0 inet dhcp
    - name: wlan0
      config: |+
        allow-hotplug wlan0
        iface wlan0 inet manual
        wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
        iface default inet dhcp
      wifi:
        ssid: PDT-01
        password: "{{ S_NETWORKING.wifi.pdt_01.password }}"
      firmware:
        package: firmware-ralink


UDEV:
  rule_files:
    - name: 99-busware.rules
      rules:
        - 'SUBSYSTEM=="tty", ATTRS{idProduct}=="204b", ATTRS{idVendor}=="03eb", ATTRS{product}=="CUL433", SYMLINK+="{{ CUL.symlinks.433 }}"'
        - 'SUBSYSTEM=="tty", ATTRS{idProduct}=="204b", ATTRS{idVendor}=="03eb", ATTRS{product}=="CUL868", SYMLINK+="{{ CUL.symlinks.868 }}"'
  vendors:
    - 03eb

