---

CUL:
  symlinks:
    433: CUL433
    868: CUL868


FHEM:
  firware_flash_support: No
  security:
    telnet:
      password: "{{ S_FHEM.security.telnet.password }}"
    web:
      user: fhem
      password: "{{ S_FHEM.security.web.password }}"
  io:
    devices:
      cul:
        433:
          device_path: "/dev/{{ CUL.symlinks.433 }}"
        868:
          device_path: "/dev/{{ CUL.symlinks.868 }}"
  intertechno:
    # siehe http://www.fhemwiki.de/wiki/Intertechno_Code_Berechnung
    devices:
      schalter_1A:
        code: 000000000F
        alias: Weihnachtsbaum
        group: Licht
        gen_type: light
        rooms:
          - Wohnzimmer
          - Homekit
      schalter_1B:
        code: 0000F0000F
        alias: Discobaum
        group: Licht
        gen_type: light
        rooms:
          - Wohnzimmer
          - Homekit
      schalter_1C:
        code: 00000F000F
        gen_type: light
        group: Licht
        rooms: [ hidden ]
      schalter_2A:
        code: 000000F00F
        alias: Fische
        group: Licht
        gen_type: light
        rooms:
          - Flur
          - Homekit
      schalter_2B:
        code: 0000F0F00F
        alias: Fischbubbles
        group: Schalter
        gen_type: switch
        rooms:
          - Flur
          - Homekit
      schalter_2C:
        code: 00000FF00F
        gen_type: light
        group: Licht
        rooms: [ hidden ]
      schalter_3A:
        code: 0000000F0F
        group: Licht
        gen_type: light
        rooms: [ hidden ]
      schalter_3B:
        code: 0000F00F0F
        group: Licht
        gen_type: light
        rooms: [ hidden ]
      schalter_3C:
        code: 00000F0F0F
        gen_type: light
        group: Licht
        rooms: [ hidden ]
  homematic:
    hmId: "{{ S_FHEM.homematic.hmId }}"
    devices:
      schalter_HM1:
        address: 3705C3
        serialNr: MEQ0273212
        subType: powerMeter
        IODev: CUL_868
        actCycle: 000:10
        actStatus: alive
        autoReadReg: 4_reqStatus
        expert: 2_full
        firmware: 1.6
        model: HM-ES-PMSw1-Pl
        webCmd: "getConfig:clear msgEvents"
        channels:
          - name: Switch
            channel: 01
            subType: switch
            alias: "Papierleuchte am Esstisch"
            group: Licht
            gen_type: light
            icon: "light_light"
            rooms: [ Wohnzimmer, Homekit ]
          - name: Power
            channel: 02
            rooms: [ hidden ]
          - name: PowerSenor
            channel: 03
            rooms: [ hidden ]
          - name: CurrentSenor
            channel: 04
            rooms: [ hidden ]
          - name: VoltageSenor
            channel: 05
            rooms: [ hidden ]
          - name: FrequencySenor
            channel: 06
            rooms: [ hidden ]
      schalter_HM2:
        address: 3705E8
        serialNr: MEQ0273249
        subType: powerMeter
        IODev: CUL_868
        actCycle: 000:10
        actStatus: alive
        autoReadReg: 4_reqStatus
        expert: 2_full
        firmware: 1.6
        model: HM-ES-PMSw1-Pl
        webCmd: "getConfig:clear msgEvents"
        channels:
          - name: Switch
            subType: switch
            channel: 01
            alias: "Papierleuchte am Fernseher"
            group: Licht
            gen_type: light
            icon: "light_light"
            rooms: [ Wohnzimmer, Homekit ]
          - name: Power
            channel: 02
            rooms: [ hidden ]
          - name: PowerSenor
            channel: 03
            rooms: [ hidden ]
          - name: CurrentSenor
            channel: 04
            rooms: [ hidden ]
          - name: VoltageSenor
            channel: 05
            rooms: [ hidden ]
          - name: FrequencySenor
            channel: 06
            rooms: [ hidden ]
      schalter_HM3:
        address: 37C3FD
        serialNr: MEQ0269952
        subType: powerMeter
        IODev: CUL_868
        actCycle: 000:10
        actStatus: alive
        autoReadReg: 4_reqStatus
        expert: 2_full
        firmware: 1.6
        model: HM-ES-PMSw1-Pl
        webCmd: "getConfig:clear msgEvents"
        channels:
          - name: Switch
            subType: switch
            channel: 01
            alias: "Stehlampe"
            group: Licht
            gen_type: light
            icon: "light_light"
            rooms: [ Wohnzimmer, Homekit ]
          - name: Power
            channel: 02
            rooms: [ hidden ]
          - name: PowerSenor
            channel: 03
            rooms: [ hidden ]
          - name: CurrentSenor
            channel: 04
            rooms: [ hidden ]
          - name: VoltageSenor
            channel: 05
            rooms: [ hidden ]
          - name: FrequencySenor
            channel: 06
            rooms: [ hidden ]
  extra: |+
    # ========================
    # Additional Devices
    # ========================
    #
    define Fernseher STV 192.168.101.12
    attr Fernseher icon it_television
    attr Fernseher devStateIcon .*on:audio_volume_high .*off:audio_volume_mute .*:unknown
    attr Fernseher room Wohnzimmer
    attr Fernseher webCmd mute on:mute off
  end:


FHEM_TABLET_UI:
  update: No
  install_dir: /opt/fhem-tablet-ui
  rooms:
    Wohnzimmer:
      #devices: "{{ FHEM.intertechno.devices|selectattr('alias', 'defined')|list + FHEM.homematic.devices|map(attribute='channels')|map('first')|list }}"
      devices:
        schalter_HM1_Switch: "{{ FHEM.homematic.devices['schalter_HM1'].channels|first }}"
        schalter_HM2_Switch: "{{ FHEM.homematic.devices['schalter_HM2'].channels|first }}"
        schalter_HM3_Switch: "{{ FHEM.homematic.devices['schalter_HM3'].channels|first }}"
        schalter_1A: "{{ FHEM.intertechno.devices['schalter_1A'] }}"
        schalter_1B: "{{ FHEM.intertechno.devices['schalter_1B'] }}"
    Flur:
      devices:
        schalter_2A: "{{ FHEM.intertechno.devices['schalter_2A'] }}"
        schalter_2B: "{{ FHEM.intertechno.devices['schalter_2B'] }}"


HOMEBRIDGE:
  security:
    username: "{{ S_HOMEBRIDGE.security.username }}"
    pin: "{{ S_HOMEBRIDGE.security.pin }}"
  modules:
    - homebridge
    - homebridge-fhem
    - homebridge-sonos
  accessories:
    - accessory: "Sonos"
      name: "Wohnzimmer Boxen"
      room: "Wohnzimmer"
    - accessory: "Sonos"
      name: "Arbeitszimmer Boxen"
      room: "Arbeitszimmer"
  platforms:
    fhem:
      security:
        user: "{{ FHEM.security.web.user }}"
        password: "{{ FHEM.security.web.password }}"
  nodejs:
    version: node-v4.2.3-linux-armv7l
    download_url: https://nodejs.org/dist/v4.2.3/node-v4.2.3-linux-armv7l.tar.gz


NETWORKING:
  use_wifi: Yes
  interfaces:
    - name: eth0
      config: |+
        auto eth0
        iface eth0 inet dhcp
    - name: wlan0
      config: |+
        allow-hotplug wlan0
        iface wlan0 inet manual
        wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
        iface default inet dhcp
      wifi:
        ssid: PDT-02
        password: "{{ S_NETWORKING.wifi.pdt_02.password }}"
      firmware:
        package: firmware-ralink


UDEV:
  rule_files:
    - name: 99-busware.rules
      rules:
        - 'SUBSYSTEM=="tty", ATTRS{idProduct}=="204b", ATTRS{idVendor}=="03eb", ATTRS{product}=="CUL433", SYMLINK+="{{ CUL.symlinks.433 }}"'
        - 'SUBSYSTEM=="tty", ATTRS{idProduct}=="204b", ATTRS{idVendor}=="03eb", ATTRS{product}=="CUL868", SYMLINK+="{{ CUL.symlinks.868 }}"'
  vendors:
    - 03eb

